name: Sync Fork

on:
  schedule:
    - cron: '0 1 1 * *' # every month
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          owner: framer
          base: master
          head: master
